dj_project/urls.py
# 设计路由视图和模板，这里是根目录路由
from django.contrib import admin
from django.urls import path, re_path

''' 想在 Django 项目中配置处理 URL，
应该使用 Django 提供的内置模块（包），函数/方法（文件/类）
`django.conf.urls.url` 是 Django 1.x 版本中的 URL 配置方法，
但在 Django 2.x 及更新版本中，推荐使用 `django.urls.re_path`
 或 `django.urls.path` 进行 URL 配置。
'''

from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from timing_blog.feed import LatestEntriesFeed
from timing_blog import views as blog_views

'''
 是用于包含其他 URL 配置的常用模块。
 它是 Django 中的标准功能，通常不会与特定环境或版本不兼容。
 在Django 2.x及更高版本中，`include` 函数已经被移动到 `django.urls` 模块中，
 所以如果你已经导入了 `from django.urls import path`，
 通常情况下就不需要再导入 `from django.conf.urls import include`。
'''

# 快捷方式快速生成网络地图，不需要给站点地图单独写视图模块
# 直接在URLconfer里面获取对象，然后传递参数设置URL，
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from timing_blog.models import Entry
info_dict = {
    # 生成一个字典，查询集，是所有博客都要放进来站点里面
    'queryset': Entry.objects.all(),
    'date_field': 'modified_time'
}
from timing_blog import views
urlpatterns = [
                  re_path(r'^$', blog_views.index),
                  re_path(r'^admin/', admin.site.urls),
                  re_path(r'^timing_blog/', include('timing_blog.urls')),
                  #     每个以timing_blog开头的路由都把它转发到timing_blog下面的urls
                  # 定义 URL 二级路由
                  re_path(r'^latest/feed/$', LatestEntriesFeed()),
                  re_path(r'^comments/', include('django_comments.urls')),
                  # 凡是走comments的URL都转发到django_comments.urls里面
                  re_path(r'^sitemap\.xml$', sitemap,{'sitemaps':{'timing_blog':GenericSitemap(info_dict,priority=0.6)}},name='django.contrib.sitemaps.views.sitemap'),
                  re_path(r'^qa/', views.handle_question, name='handle_question'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 设定图片的URL找到图片内容，类似于下面的这个
# re_path(r'^(?P<blog_id>[0-9]+)', views.detail, name='blog_detail'),
handler403 = blog_views.permission_denied
# 403禁止访问，权限不允许  ，写个视图专门处理这个
handler404 = blog_views.page_not_found
# 404页面不存在，
handler500 = blog_views.page_error
# 500服务器错误

timing_blog/urls.py
# 设计路由视图和模板，这里是二级目录路由
from django.urls import path, re_path
''' 
想在 Django 项目中配置处理 URL，
应该使用 Django 提供的内置模块（包），函数/方法，文件/类
`django.conf.urls.url` 是 Django 1.x 版本中的 URL 配置方法，
但在 Django 2.x 及更新版本中，推荐使用 `django.urls.re_path`
 或 `django.urls.path` 进行 URL 配置。
'''
from . import views

app_name = 'timing_blog'
urlpatterns = [
    re_path(r'^$', views.index, name='blog_index'),
    # 代表域名后面什么都没有
    re_path(r'^(?P<blog_id>[0-9]+)/$', views.detail, name='blog_detail'),
    # 详情页，接受一个数字作为参数，命名为 blog_id,给每篇文章detail设计好了一个url
    re_path(r'^category/(?P<category_id>[0-9]+)/$', views.category, name='blog_category'),
    re_path(r'^tag/(?P<tag_id>[0-9]+)/$', views.tag, name='blog_tag'),
    re_path(r'^search/$', views.search, name='blog_search'),
    re_path(r'^archives/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', views.archives, name='blog_archives'),
    re_path(r'^qa/', views.handle_question, name='handle_question'),
    re_path(r'^wechat_login/', views.wechat_login, name='wechat_login'),
    re_path(r'^reply/(?P<comment_id>\d+)/$', views.reply, name='comment_reply'),

]

# 定义 URL 二级路由
'''
 $表示什么都没有，空，直接就是表示查看首页，并提供一个路由反向查询名
    都是为了让我们这个blog能够独立出来。
能够成为一个隔离的环境，不会跟其他的APP冲突，
以后也要使用这种技巧，看起来麻烦，但实际上受益无穷，
尤其是项目很大的时候。所以建议在这写一个APP name。
这就是给这个博客提供一个命名空空间，
以后所有的路由它的名字都以这个开头，
防止APP它之间URL反向解析，有可能会重名
其实这里name='blog_index可以不用前缀，但是填上去更显眼
'''

timing_blog/models.py
from django.contrib.auth.models import User
# 库里的user方法
from django.db import models
from django.urls import reverse


# 内置模块（包、库），文件/类()，函数/方法def，变量/对象

# 模型、组成（变量，对象）、约束（参数）、指向、别名、回组、元类

# Create your models here.
class Category(models.Model):  # 类别
    # 自建模型
    name = models.CharField(max_length=128, verbose_name='博客分类')

    # 组成模型的字段 和 对应的约束条件/指向模型，别名

    def __str__(self):
        return self.name  # 打印名字而非生硬的对象

    class Meta:  # 元类、属性字段
        verbose_name = "博客分类"
        verbose_name_plural = '博客分类'  # 复数接轨


class Tag(models.Model):
    name = models.CharField(max_length=128, verbose_name='博客标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "博客标签"
        verbose_name_plural = '博客标签'


class Entry(models.Model):
    title = models.CharField(max_length=128, verbose_name='文章标题')

    author = models.ForeignKey(User, verbose_name='博客作者', on_delete=models.CASCADE)
    # 外键，主键，用户模型，直接使用内置的user模型
    img = models.ImageField(upload_to='blog_images', null=True, blank=True, verbose_name='博客配图')

    body = models.TextField(verbose_name='博客正文')

    abstract = models.TextField(max_length=256, blank=True, null=True, verbose_name='博客摘要')

    visiting = models.PositiveIntegerField(default=0, verbose_name='博客访问量')
    # 正整数，刚开始为0
    category = models.ManyToManyField('Category', verbose_name='博客分类')

    tags = models.ManyToManyField('Tag', verbose_name='博客标签')
    # 多对多的关系模型
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    modified_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    # 修改时间

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('timing_blog:blog_detail', kwargs={'blog_id': self.id})

    # 生成某一篇博客的URL绝对路径  参数通过字典键获取，为解析提供参数生成完整的url
    def increase_visiting(self):
        self.visiting += 1
        self.save(update_fields=['visiting'])

    # 保存点击量的数据并显示，指定保存字段
    class Meta:
        ordering = ['-created_time']
        # 获取博客数据，写这段方便排序，且自定义评论中也需要。
        # 学会习惯给需要查询的对象添加一个默认排序值。不添加ID会有问题，一旦碰到就麻烦
        verbose_name = "博客"
        verbose_name_plural = '博客'

timing_blog/views.py
import markdown

from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from . import models
import pygments
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from django.http import JsonResponse
from openai import Completion
import openai
import json
from django.http import JsonResponse

from django.shortcuts import redirect
from django_comments import models as comment_models
from django_comments.models import Comment

def wechat_login(request):
    # 生成微信登录链接
    wechat_login_url = 'https://open.weixin.qq.com/connect/qrconnect?appid=YOUR_APPID&redirect_uri=YOUR_REDIRECT_URI&response_type=code&scope=snsapi_login&state=STATE#wechat_redirect'
    return redirect(wechat_login_url)


def handle_question(request):
    if request.method == "POST":
        data = json.loads(request.body)
        question = data.get("question", "")

        # 调用 ChatGPT 来生成答案
        openai.api_key = "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" # 替换为您的密钥
        completion = openai.Completion()
        response = completion.create(
            model="gpt-3.5-turbo",
            prompt=[
                {
                    "role": "user",
                    "content": question
                }
            ],
            max_tokens=100,
            stop=["\n"]
        )

        # 返回答案给前端
        return JsonResponse({"answer": response.choices[0].text})
    else:
        return JsonResponse({"error": "Only POST requests are allowed."}, status=405)

# 内置了一个分页的功能，导入分页的类，分页器，空页，不是整数页面的三个功能导入进来
# 从url找到视图，视图除了引出对应的页面，还要收录模型，才能显示信息。
# Create your views here.
def make_paginator(objects, page, num=6):
    # 写一个方法 自定义分页，对象的列表，查看第几页，每页显示几个
    paginator = Paginator(objects, num)
    # 生成提供分页工具的对象（分页器，5文一页），所有的博客，每页的数量
    try:
        # 获取当前的对象列表
        object_list = paginator.page(page)
    # 以下是一些异常的处理情况
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)
    return object_list, paginator


# 这段从github找到一个美观一点的分页器显示，不是重点，不难理解，简单但繁琐，多
# 就像前端一样，所以直接借鉴他人，拿来主义，直接就是拿来用就行了
def pagination_data(paginator, page):
    """
    用于自定义展示分页页码的方法
    :param paginator: Paginator类的对象
    :param page: 当前请求的页码
    :return: 一个包含所有页码和符号的字典
    """
    if paginator.num_pages == 1:
        # 如果无法分页，也就是只有1页不到的内容，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
        return {}
    # 当前页左边连续的页码号，初始值为空
    left = []

    # 当前页右边连续的页码号，初始值为空
    right = []

    # 标示第 1 页页码后是否需要显示省略号
    left_has_more = False

    # 标示最后一页页码前是否需要显示省略号
    right_has_more = False

    # 标示是否需要显示第 1 页的页码号。
    # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
    # 其它情况下第一页的页码是始终需要显示的。
    # 初始值为 False
    first = False

    # 标示是否需要显示最后一页的页码号。
    # 需要此指示变量的理由和上面相同。
    last = False

    # 获得用户当前请求的页码号
    try:
        page_number = int(page)
    except ValueError:
        page_number = 1
    except:
        page_number = 1

    # 获得分页后的总页数
    total_pages = paginator.num_pages

    # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
    page_range = paginator.page_range

    if page_number == 1:
        # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
        # 此时只要获取当前页右边的连续页码号，
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
        # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        right = page_range[page_number:page_number + 4]

        # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
        # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
        if right[-1] < total_pages - 1:
            right_has_more = True

        # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
        # 所以需要显示最后一页的页码号，通过 last 来指示
        if right[-1] < total_pages:
            last = True

    elif page_number == total_pages:
        # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
        # 此时只要获取当前页左边的连续页码号。
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
        # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

        # 如果最左边的页码号比第 2 页页码号还大，
        # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
        if left[0] > 2:
            left_has_more = True

        # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
        # 所以需要显示第一页的页码号，通过 first 来指示
        if left[0] > 1:
            first = True
    else:
        # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
        # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        right = page_range[page_number:page_number + 2]

        # 是否需要显示最后一页和最后一页前的省略号
        if right[-1] < total_pages - 1:
            right_has_more = True
        if right[-1] < total_pages:
            last = True

        # 是否需要显示第 1 页和第 1 页后的省略号
        if left[0] > 2:
            left_has_more = True
        if left[0] > 1:
            first = True

    data = {
        'left': left,
        'right': right,
        'left_has_more': left_has_more,
        'right_has_more': right_has_more,
        'first': first,
        'last': last,
    }
    return data


def index(request):
    entries = models.Entry.objects.all()
    #     把模型的所有文章都导进来
    page = request.GET.get('page', 1)
    # 从request的GET方法里获取page的值
    entry_list, paginator = make_paginator(entries, page)
    # 这个entry-list就是选择当前页的数量有哪几个，就是类似于主函数调用自定义函数
    page_data = pagination_data(paginator, page)
    # 生成美化版的分页标签，方法借鉴别人的写在了上面的自定义函数里面
    return render(request, 'timing_blog/index.html', locals())


'''渲染第一个参数为request，
第二个视图文件视图放在timing_blog下面的index点HTML。
然后给个locals，把当前所有的变量全部打到那个打包成字典传进去，、
在timing_blog下面创建一个目录，叫做template，
在templates下面再创建个目录，叫做timing_blog
'''


def detail(request, blog_id):
    # entry = models.Entry.objects.get(id=blog_id)
    entry = get_object_or_404(models.Entry, id=blog_id)
    # 把某篇具体的文章导进来，然后就会执行增加的方法
    md = markdown.Markdown(extensions=[
        # 类，这个参数是个列表，提供一些语法内容
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        # 高亮
        'markdown.extensions.toc',
    ])
    # 定义了一个md，让文章的body转化成这个新的格式
    entry.body = md.convert(entry.body)
    entry.toc = md.toc
    # 列表，目录
    entry.increase_visiting()
    comment_list = list()

    def get_comment_list(comments):
        for comment in comments:
            comment_list.append(comment)
            children = comment.child_comment.all()
            if len(children) > 0:
                get_comment_list(children)

    top_comments = Comment.objects.filter(object_pk=blog_id, parent_comment=None,
                                          content_type__app_label='timing_blog').order_by('-submit_date')

    get_comment_list(top_comments)
    return render(request, 'timing_blog/detail.html', locals())


def category(request, category_id):
    # c = models.Category.objects.get(id=category_id)
    # 获取分类ID传过来的参数的对象。
    c = get_object_or_404(models.Category, id=category_id)
    # 确保传过来的参数不会出问题，出问题我就404
    entries = models.Entry.objects.filter(category=c)
    # 过滤器，这个分类下有哪些博客
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'timing_blog/index.html', locals())


def tag(request, tag_id):
    # t = models.Tag.objects.get(id=tag_id)
    t = get_object_or_404(models.Tag, id=tag_id)
    # 如上，目录和细节，这个是标签
    if t.name == "全部":
        entries = models.Entry.objects.all()
    else:
        entries = models.Entry.objects.filter(tags=t)

    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'timing_blog/index.html', locals())


def search(request):
    keyword = request.GET.get('keyword', None)
    # 获取关键字，如果没有那就是none
    if not keyword:
        error_msg = "请输入关键字"
        # 如果没有关键字，打印一个错误
        return render(request, 'timing_blog/index.html', locals())
    # 如果有关键字，那就搜索内容
    entries = models.Entry.objects.filter(Q(title__icontains=keyword)
                                          | Q(body__icontains=keyword)
                                          | Q(abstract__icontains=keyword))
    # Q搜索，Q函数，是专门用于搜索的，django内置提供的过滤函数。

    page = request.GET.get('page', 1)
    # 默认开始显示页数
    entry_list, paginator = make_paginator(entries, page)
    # 分页器，每页显示什么东西
    page_data = pagination_data(paginator, page)
    # 美化过的页数选择框
    return render(request, 'timing_blog/index.html', locals())


def archives(request, year, month):
    entries = models.Entry.objects.filter(created_time__year=year, created_time__month=month)
    # 类，形参导入数据变成实参，导进变量对象
    # 过滤器，这个分类下有哪些博客
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'timing_blog/index.html', locals())


def permission_denied(request, exception):
    return render(request, 'timing_blog/403.html', locals())


def page_not_found(request, exception):
    return render(request, 'timing_blog/404.html', locals())


def page_error(request):
    return render(request, 'timing_blog/500.html', locals())
def reply(request, comment_id):
    # if not request.session.get('login', None) and not request.user.is_authenticated():
    #     return redirect('/')
    # 让它不登陆也能回复
    parent_comment = get_object_or_404(comment_models.Comment, id=comment_id)
    return render(request, 'timing_blog/reply.html', locals())

timing_blog/templates/timing_blog/detail.html
{#<h1>博客{{ blog_id }}页面</h1>#}
{#自动随views里的detail类的id属性变化而变化#}
{% extends 'timing_blog/base.html' %}
{% load static %}
{% load comments %}
{% block title %}博客详细页面{% endblock %}
{% block css %}
    <link href="{% static 'timing_blog/css/github.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
<div class="container">
    {#屏幕显示自适应#}
    <div class="row">
        {#生成一行，框架的要求#}
        <div class="col-md-9">
            {#占十二个位置，本来想剩三个给侧边栏#}
            <h1>{{ entry.title }}</h1>
            <p>
                <strong>{{ entry.author }}</strong>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ entry.created_time|date:'Y年m月d日' }}
                {#python模板内置的一种时间格式，具体可用格式可查表#}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;分类：
                {% for category in entry.category.all %}
                    {#类别模型（类）把在文章模型的每个类别中都列出来#}
                    <a href="{% url 'timing_blog:blog_category' category.id %}">{{ category.name }}</a>
                {% endfor %}

                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;标签：
                {% for tag in entry.tags.all %}
                    {#变量（对象）把在文章模型的每个标签的全部都导入进来#}
                    <a href={% url 'timing_blog:blog_tag' tag.id %}>{{ tag.name }}</a>
                    {#生成一个链接，并由导入进tag变量的模型tags的每个实参，去提供链接里年月的参数#}
                {% endfor %}

                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;浏览量：
                {{ entry.visiting }}
            </p>
            {% if entry.img %}
                <div><img src="{{ entry.img.url }}" alt="博客配图" width="40%"/></div>
            {% endif %}
            <hr />
            {#分行栏，br是回车，没有横线#}
            <p>
                {{ entry.body|safe }}
                {#python内置的safe安全过滤器，可以让body显示HTML文本的格式，而非全部文本#}
            </p>

            <div class="row">
                <hr />
                {% get_comment_form for entry as form %}
                {% get_comment_count for entry  as comment_count %}
                <h3>评论总数： {{ comment_count }}</h3>
                <hr />
            </div>
            {# 评论表单 #}
            <div class="row">
                <form class="form-horizontal" action="{% comment_form_target %}" method="post">
{#                    <form class="form-horizontal" action="{% url 'timing_blog:blog_detail' entry.id %}" method="post">#}

                    {% csrf_token %}
                    <div class="form-group">
                        <label for="input_title" class="pull-left control-label">评论标题：</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="comment_title" id="input_title" placeholder="请输入标题" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_comment" class="pull-left control-label">评论内容:</label>
                        <div class="col-sm-6">
                            <textarea style="resize:none;" class="form-control" rows=6 name="comment" id="input_comment" placeholder="在此输入评论" required></textarea>
                        </div>
                    </div>
                    <span style="display: none;">{{ form.honeypot }}</span>
                    {{ form.content_type }}
                    {{ form.object_pk }}
                    {{ form.timestamp }}
                    {{ form.security_hash }}
                    <input type="hidden" name="next" value="{% url 'timing_blog:blog_detail' entry.id %}" />
                    <input  name="parent_id" type="hidden" value="-1" />
                    <input  name="level" type="hidden" value="0" />

                    <div class="form-group col-sm-7">
                        <div class="pull-left" style="margin-left: 68px;">
                            <button type="reset"  class="btn btn-default"><span class="glyphicon glyphicon-repeat"></span>&nbsp;&nbsp;重置</button>
                        </div>
                        <div class="pull-right" style="margin-right: 12px;">
                            <button type="submit" class="btn btn-success" id="id_submit"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;评论</button>
                        </div>
                    </div>
                </form>
            </div>
            <hr />
            {# 评论显示区 #}
            <div class="row">
                {% for comment in comment_list %}
                    <div class="single_comment" style="margin-left: {{ comment.level }}em">
                        <div>
                            {% if comment.user_img %}
                                <img src="{{ comment.user_img }}" alt="user_image" />
                            {% else %}
                                <img src="{% static 'timing_blog/images/admin_image.jpg' %}" />
                            {% endif %}
                        </div>
                        <div class="col-md-11 comment-content" style="margin-bottom: 10px;">
                            <strong>{{ comment.comment_title }}</strong>
                            <div>
                                {% if comment.parent_comment %}
                                    {{ comment.user_name }}{{ request.user }}
                                    <i class="glyphicon glyphicon-share-alt"></i>
                                    {{ comment.parent_comment.user_name }}{{ request.user }}
                                {% else %}
                                    By&nbsp;&nbsp;
                                    {{ comment.user_name }}{{ request.user }}
                                    &nbsp;&nbsp;&nbsp;On&nbsp;&nbsp;
                                {% endif %}
                                <em>{{ comment.submit_date }}</em>
                                &nbsp;&nbsp;&nbsp;<a href="{% url 'timing_blog:comment_reply' comment.id %}">回复</a>
                            </div>
                            <br />
                            <p>{{ comment.comment }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            {#一行根据约定就是12个占位，侧边栏这里占3列#}
            {% block toc %}
                <div class="row">
                    {#独占一行，要分行#}
                    <div class="widget">
                        {#生成一个侧边栏的类#}
                        <h3>博客目录:</h3>
                        {#把博客目录全部列出来#}
                        {{ entry.toc|safe }}
                        {#safe,就可以改成HTML文本显示，而不是MARKdown格式，#}
                        {# 博客文章的目录，即文章的小标题，点就可以去到对应的文章部分#}
                    </div>
                </div>
                <hr />
            {% endblock %}
            {% include 'timing_blog/right_side_bar.html' %}
        </div>
    </div>
</div>
{% endblock %}